version: '3'
services:
  svc-lbh-dev-be-nodeserver:
    build: .
    restart: always
    container_name: ctn-lbh-dev-be-nodeserver
    ports:
      - "5446:4000"
networks:
    default:
      external:
        name: nw-lbh