version: '3'
services:
  lbh_be_dev:
    image: bieberlee/luvbeenhere_backend:latest
    restart: always
    container_name: lbh_be_dev
    ports:
      - "5446:4000"
networks:
    default:
      external:
        name: nw-lbh